version: '3'

services:
  # React application service
  react-app:
    build:
      context: ./client/
      dockerfile: Dockerfile.react
    ports:
      - "4173:4173"
    volumes:
      - ./client:/app
    command: ["npx", "vite", "preview", "--host", "0.0.0.0"]

  # Django application service
  django-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/home/OtelApp
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  # Database service
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres