version: '3'

services:
  # React uygulaması için servis
  react-app:
    build:
      context: ./client/
      dockerfile: Dockerfile.react
    networks:
      - shared-network
    ports:
      - "4173:4173"
    command: ["npx", "vite", "preview", "--host", "0.0.0.0"]

  # Django uygulaması için servis
  django-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    networks:
      - shared-network
networks:
  shared-network: