# Generated by Django 4.2.7 on 2023-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Animal')),
                ('width', models.IntegerField(verbose_name='Animal Width')),
                ('height', models.IntegerField(verbose_name='Animal Height')),
                ('tur', models.CharField(max_length=50)),
                ('yas', models.IntegerField()),
                ('renk', models.CharField(blank=True, max_length=50, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
