# Adım 1: Python tabanlı bir görüntü kullan
FROM python:3.12

# Çalışma dizinini ayarla
WORKDIR /

# Bağımlılıkları kopyala ve kur
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Adım 2: Uygulama kodunu kopyala
COPY . .

# Uygulamayı başlat
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]