# Generated by Django 4.2.7 on 2023-11-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('createAt', models.DateTimeField(auto_now=True, verbose_name='Create At')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryblog', verbose_name='Category Name')),
            ],
        ),
    ]
