# Generated by Django 4.2.7 on 2023-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categoryblog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryblog',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
