# Generated by Django 4.2.7 on 2023-11-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_categoryblog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryblog',
            options={'verbose_name': 'Category Blog'},
        ),
    ]
