# Generated by Django 4.2.7 on 2023-11-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_categoryblog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryblog',
            options={'verbose_name_plural': 'Category Blog'},
        ),
    ]
