# Generated by Django 4.2.7 on 2023-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_options_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.ManyToManyField(to='app.categoryblog', verbose_name='Categories'),
        ),
    ]
