# Generated by Django 4.2.7 on 2023-11-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_blog_name_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
