# Generated by Django 4.2.7 on 2023-11-29 05:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_labelcategory_blog_category_blog_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelcategory',
            options={'verbose_name_plural': 'Label Category'},
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Article Title')),
                ('content', models.TextField(verbose_name='Article Content')),
                ('createAt', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='title')),
                ('label', models.ManyToManyField(to='app.labelcategory', verbose_name="Label's")),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
    ]
